version: '{build}'
image:
- Ubuntu1804
- Visual Studio 2017
configuration: Release
platform: x64
cache:
- '%USERPROFILE%\.conan'
- premake5.exe
- premake5
install:
- ps: >-
    if ($isWindows) {
        if (-Not (Test-Path premake5.exe)) {
            Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-windows.zip' -FileName 'premake5.zip'            

            7z x premake5.zip
        }
    } else {
        if (-Not (Test-Path premake5)) {
            Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz' -FileName 'premake5.tar.gz'

            tar -xvf premake5.tar.gz
        }
    }
    $Env:PATH += ";$Env:PYTHON/Scripts/"
    pip install conan
    conan remote clean
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    mkdir build
    cd build
    conan install ..
build_script:
- ps: >-
    if ($isWindows) {
        ./premake5.exe vs2017
        msbuild "desktop-canvas.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    } else {
        ./premake5 gmake
        sh -c 'CXX=g++-8 make config=debug_x64'
    }
