version: '{build}'
image:
- Ubuntu1804
- Visual Studio 2017
configuration: Release
platform: x64
install:
- ps: >-
    if ($isWindows) {
        $Env:VCPKG_ROOT="c:\tools\vcpkg"
        vcpkg install sdl2:x64-windows sdl2-mixer:x64-windows sdl2-ttf:x64-windows asio:x64-windows websocketpp:x64-windows
    } else {
        $Env:VCPKG_ROOT="$Env:APPVEYOR_BUILD_FOLDER/vcpkg"
        if (-Not (Test-Path vcpkg)) {
            git clone https://github.com/Microsoft/vcpkg.git
            cd vcpkg
            sh bootstrap-vcpkg.sh
            cd ..
        }
        cd vcpkg
        ./vcpkg install sdl2:x64-linux sdl2-mixer:x64-linux sdl2-ttf:x64-linux asio:x64-linux websocketpp:x64-linux zlib:x64-linux
        cd ..
    }
cache:
- vcpkg
- c:\tools\vcpkg\installed
build_script:
- ps: >-
    mkdir build

    cd build

    if ($isWindows) {
        cmake -G "Visual Studio 15 2017 Win64" ..
        msbuild "desktop-canvas.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    } else {
        sh -c 'CXX=g++-8 cmake -G \"Unix Makefiles\" ..'
        make all
    }