jobs:
  - job: Ubuntu
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - pwsh: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-8
          git clone https://github.com/jackbister/vcpkg.git ~/vcpkg
          sh ~/vcpkg/bootstrap-vcpkg.sh
        displayName: init
      - pwsh: |
          $Env:VCPKG_ROOT="/home/vsts/vcpkg"
          sudo apt-get install yasm
          ~/vcpkg/vcpkg install sdl2:x64-linux sdl2-mixer:x64-linux sdl2-ttf:x64-linux asio:x64-linux websocketpp:x64-linux zlib:x64-linux
        displayName: setup
      - pwsh: |
          mkdir build
          cd build
          $Env:VCPKG_ROOT="/home/vsts/vcpkg"
          sh -c 'CXX=g++-8 cmake -G \"Unix Makefiles\" ..'
          make all
        displayName: build
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - pwsh: |
          git clone https://github.com/jackbister/vcpkg.git \vcpkg
          \vcpkg\bootstrap-vcpkg.bat
        displayName: init
      - pwsh: |
          $Env:VCPKG_ROOT="\vcpkg"
          \vcpkg\vcpkg.exe" install sdl2:x64-windows sdl2-mixer:x64-windows sdl2-ttf:x64-windows asio:x64-windows websocketpp:x64-windows
        displayName: setup
      - pwsh: |
          mkdir build
          cd build
          $Env:VCPKG_ROOT="\vcpkg"
          cmake -G "Visual Studio 15 2017 Win64" ..
          msbuild "desktop-canvas.sln" /m /verbosity:minimal
        displayName: build
