trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- pwsh: |
    if ($isLinux) {
      apt-get install g++-8
    }
    git clone https://github.com/jackbister/vcpkg.git ~/vcpkg
    sh ~/vcpkg/bootstrap-vcpkg.sh
  displayName: init
- pwsh: |
    if ($isWindows) {
      $Env:VCPKG_ROOT="C:\Users\vsts\vcpkg"
      ~/vcpkg install sdl2:x64-windows sdl2-mixer:x64-windows sdl2-ttf:x64-windows asio:x64-windows websocketpp:x64-windows
    } else {
      $Env:VCPKG_ROOT="/home/vsts/vcpkg"
      apt-get install yasm
      ~/vcpkg/vcpkg install sdl2:x64-linux sdl2-mixer:x64-linux sdl2-ttf:x64-linux asio:x64-linux websocketpp:x64-linux zlib:x64-linux
    }
  displayName: setup
- pwsh: |
    mkdir build
    cd build
    if ($isWindows) {
      cmake -G "Visual Studio 15 2017 Win64" ..
      msbuild "desktop-canvas.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    } else {
      sh -c 'CXX=g++-8 cmake -G \"Unix Makefiles\" ..'
      make all
    }
  displayName: build
